name: check weather

on:
    push:
        branches: [ "main" ]

    schedule:
        - cron: '*/10 * * * *' #runs every 10 minutes

jobs:
    Do:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.12' 
            # - run: python my_script.py

            - name: install python packages
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: execute script
              run: python main.py

    Commit:
        runs-on: ubuntu-latest
        steps:
            - name: commit files
              run: |
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add -A
                git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
            
            - name: push changes
              uses: ad-m/github-push-action #@v0.6.0
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                branch: main 
